### ISSUE TITLE
IOS Build: research

### ISSUE THREAD

**Issue by DenisRybas** [DenisRybas/tp-project#9]
Посмотреть, можно ли без аккаунта Apple сбилдить проект по IOS

**Comment by YellowShark** [comment]
You do not need to have a developer account if you are not publishing. However, you will have to open your app in Xcode and go to the Signing & Capabilities tab under Runner to set a Team in order to build. This can be any Apple ID. Using this method, you will not be able to just send the .ipa to your friends and them easily install it. You will need to push to their phones via Xcode.

**Comment by SP-organization** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IOS build: research](https://trello.com/c/5sUm8xS6/10-ios-build-research)
